### ISSUE TITLE
Missing profile.

### ISSUE THREAD

**Issue by mbaggerc** [ZONESTAR3D/Slicing-Guide#2]
I follow the guide for Prusa slicer, but in the slicer I don't have the option to choose Z9+One color. Only other options like Z9+E4 HOTEND, Z9+M3 HOTEND and Z9+M4 HOTEND. Thanks.

**Comment by ZONESTAR3D** [comment]
please download the newest zip file again:
https://github.com/ZONESTAR3D/Slicing-Guide/releases

Please note:
If you have installed PrusaSlicer before, you may still need to delete previous configurations settings before apply this Profiles.
For details, please refer to https://github.com/ZONESTAR3D/Slicing-Guide/tree/master/PrusaSlicer#if-you-have-installed-prusaslicer-before-you-may-still-need-to-delete-previous-configurations-settings-before-apply-this-profiles
