### ISSUE TITLE
Sample model but for the mixing hotend

### ISSUE THREAD

**Issue by logiclrd** [ZONESTAR3D/Slicing-Guide#3]
I really like the Z9E4_treefrog sample, but it's only available as G-code already sliced for the non-mixing hot end. Is it possible to get the original model, and if not, G code appropriate for the mixing hot-end? I did some searching but was not able to find the original STL. Maybe it's out there and I just didn't know how to search for it. Thanks!

**Comment by ZONESTAR3D** [comment]
FYI: https://www.thingiverse.com/thing:4340978

**Comment by logiclrd** [comment]
Thanks very much!
