### ISSUE TITLE
download link for Cura printing profiles is broken (/Slicing-Guide/cura)

### ISSUE THREAD

**Issue by doomducker** [ZONESTAR3D/Slicing-Guide#4]
duplicate issue to https://github.com/ZONESTAR3D/Z8T/issues/1 as it probably is in the wrong place and wont get seen

I am unable to download the printing profiles for Cura when looking at the slicing guide meaning i cannot use my 3d printer.

How to Recreate this Bug:
<ol>
  <li>go to the cura slicing guide https://github.com/ZONESTAR3D/Slicing-Guide/tree/master/cura.  </li>
  <li>find step 1</li>
  <li>above the first video/GIF you should see this line
  "Download [⬇️ Zonestar 3D Printer Profiles.](https://github.com/ZONESTAR3D/Slicing-Guide/blob/master/cura/ZONESTAR_Cura_Resources.zip) 👈Click here and then click "download" button. the last update on 2022-09-19.."</li>
  <li>click on the link where it says  " Zonestar 3D Printer Profiles. " (https://github.com/ZONESTAR3D/Slicing-Guide/blob/master/cura/ZONESTAR_Cura_Resources.zip)</li>
  <li> this should result in a github error 404 page</li>
  <li> you have now recreated my issue.</li>
  </ol>

  extra information
  windows 11
  firefox 116.0.3 (64bit)"
  github webpage
3d printer zonestar Z8T

**Comment by ZONESTAR3D** [comment]
https://github.com/ZONESTAR3D/Slicing-Guide/blob/master/cura/ZONESTAR_Cura_resources.zip
