### ISSUE TITLE
It is necessary to update the settings for the new version of the Cura slicer

### ISSUE THREAD

**Issue by kolobok55** [ZONESTAR3D/Slicing-Guide#8]
If in the new version of cura (5.7+) you add a printer according to your instructions, after clicking the slicing button, the "unexpecting error" appears, other printer profiles (in the same slicer) also stop working and give same error. If you do a clean installation, nothing changes, zonestar profile can't slice and error apears; new (other) added printers also give an error when slicing.

**Comment by pddring** [comment]
I had the same problem. Replacing fdmextruder.def.json and fdmprinter.def.json with the ones [here](https://github.com/Ultimaker/Cura/tree/main/resources/definitions) fixes the issue.

**Comment by danbi** [comment]
I had the same problem, but solved it by just removing these files from my Cura user folder. Then, the versions bundled with Cura are used.
Apparently Cura 5.6 did not need the missing setting.
